app:
  title: Contoso Developer Portal (Portfolio)
  baseUrl: http://localhost:3000
organization:
  name: Contoso
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
    - '''self'''
    - 'http:'
    - 'https:'
  cors:
    origin: http://localhost:3000
    methods:
    - GET
    - HEAD
    - PATCH
    - POST
    - PUT
    - DELETE
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  github:
  - host: github.com
    token: ${GITHUB_TOKEN}
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
    local:
      publishDirectory: packages/backend/static/docs
auth:
  providers:
    guest: {}
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
  - allow:
    - Component
    - System
    - API
    - Resource
    - Location
    - Domain
    - Group
    - User
  locations:
  - type: file
    target: ../../../catalog-info.yaml
permission:
  enabled: true
