app:
  baseUrl: ${APP_BASE_URL}
backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: ${BACKEND_PORT}
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
techdocs:
  builder: external
  publisher:
    type: local
    local:
      publishDirectory: packages/backend/static/docs
  generator:
    runIn: docker
catalog:
  locations:
  - type: file
    target: ../../../catalog-info.yaml
