app:
  baseUrl: ${APP_BASE_URL}

backend:
  baseUrl: ${BACKEND_BASE_URL}
  listen:
    port: ${BACKEND_PORT}

  # For real deployments, Backstage recommends Postgres.
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}

techdocs:
  builder: external
  publisher:
    type: local

catalog:
  locations:
    - type: file
      target: ../../../catalog-info.yaml
