using OrderProcess.Shared.Correlation;

namespace OrderProcess.Application.Contracts.Events;

/// <summary>
/// Integration event published by order-process after the order is persisted (OrderId generated by SQL).
/// </summary>
public sealed record OrderProcessedEvent(
    CorrelationId CorrelationId,
    long OrderId
);
