apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-notification
  description: SignalR notification edge for real-time order status.
  tags:
    - contoso-orders
    - azure
    - aks
    - dotnet
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: order-notification
spec:
  type: service
  lifecycle: production
  owner: group:platform
  system: contoso-orders
  dependsOn:
    - resource:default/contoso-orders-redis
    - resource:default/contoso-orders-servicebus
